version: "3.9"

services:
  backend:
    container_name: mytask_backend
    build:
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon --legacy-watch --watch src --ext ts --exec bun --no-cache src/index.ts      
    
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
